version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
    enable:
      - bodyclose
      - contextcheck
      - errcheck
      - errname
      - errorlint
      - exhaustive
      - exportloopref
      - gci
      - gocognit
      - goconst
      - gocritic
      - gocyclo
      - godot
      - gofmt
      - gofumpt
      - goimports
      - gomnd
      - goprintffuncname
      - gosec
      - gosimple
      - govet
      - ineffassign
      - misspell
      - nakedret
      - nolintlint
      - prealloc
      - predeclared
      - revive
      - staticcheck
      - stylecheck
      - typecheck
      - unconvert
      - unparam
      - unused
      - whitespace
      - bodyclose
      - contextcheck
      - errcheck
      - errname
      - errorlint
      - exhaustive
      - exportloopref
      - gci
      - gocognit
      - goconst
      - gocritic
      - gocyclo
      - godot
      - gofmt
      - gofumpt
      - goimports
      - gomnd
      - goprintffuncname
      - gosec
      - gosimple
      - govet
      - ineffassign
      - misspell
      - nakedret
      - nolintlint
      - prealloc
      - predeclared
      - revive
      - staticcheck
      - stylecheck
      - typecheck
      - unconvert
      - unparam
      - unused
        - whitespace
  
