apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac/
- manager/

images:
- name: vault-sync-operator
  newName: ghcr.io/danieldonoghue/vault-sync-operator
  newTag: v0.0.1-beta.2
