apiVersion: v1
kind: Namespace
metadata:
  name: vault-sync-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: vault-sync-operator
    app.kubernetes.io/instance: vault-sync-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kubectl