apiVersion: v1
kind: Service
metadata:
  name: vault-sync-operator-controller-manager-metrics-service
  namespace: vault-sync-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: vault-sync-operator
    app.kubernetes.io/instance: vault-sync-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    control-plane: controller-manager