apiVersion: v1
kind: Service
metadata:
  name: vault-sync-operator-controller-manager-metrics-service
  namespace: vault-sync-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: vault-sync-operator
    app.kubernetes.io/instance: vault-sync-operator
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    control-plane: controller-manager