apiVersion: v2
name: vault-sync-operator
description: A Helm chart for Vault Sync Operator - Kubernetes operator for syncing secrets from HashiCorp Vault
type: application
version: 0.1.0
appVersion: latest
keywords:
  - vault
  - secrets
  - kubernetes
  - operator
home: https://github.com/danieldonoghue/vault-sync-operator
sources:
  - https://github.com/danieldonoghue/vault-sync-operator
maintainers:
  - name: Daniel Donoghue
    email: danieldonoghue@users.noreply.github.com