# Default values for vault-sync-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/danieldonoghue/vault-sync-operator
  pullPolicy: IfNotPresent
  tag: ""  # Uses appVersion from Chart.yaml if empty

imagePullSecrets: []
  # Only needed for private registries. Example:
  # - name: ghcr-secret
  #   create: true
  #   registry: ghcr.io
  #   username: "your-username"
  #   password: "your-pat"
  #   email: "your-email"
nameOverride: ""
fullnameOverride: ""

# Vault configuration
vault:
  address: "http://vault:8200"
  role: "vault-sync-operator"
  authPath: "kubernetes"

# Controller manager configuration
controllerManager:
  # Leader election settings
  leaderElect: true
  
  # Health probe settings
  healthProbe:
    bindAddress: ":8081"
  
  # Metrics settings
  metrics:
    bindAddress: "127.0.0.1:8080"
    # Enable authentication and authorization for metrics endpoint
    # Set to false to disable authentication (not recommended for production)
    enableAuth: true
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Specifies whether a service account token secret should be created
  # Required for Kubernetes 1.24+ when using Vault Kubernetes auth
  createToken: true
  # Annotations to add to the service account
  annotations: {}
  # Annotations to add to the service account token secret
  tokenAnnotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC configuration
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  # fsGroup: 2000

# Security context for containers
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - "ALL"
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: metrics
  name: metrics

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Termination grace period
terminationGracePeriodSeconds: 10


# Namespace configuration
namespace:
  # Specifies whether a namespace should be created
  create: false  # Let Helm handle namespace creation with --create-namespace
  # Name of the namespace
  name: "vault-sync-operator-system"

# Additional environment variables
env: []
# - name: EXAMPLE_VAR
#   value: "example-value"

# Additional volumes
volumes: []
# - name: example-volume
#   configMap:
#     name: example-configmap

# Additional volume mounts
volumeMounts: []
# - name: example-volume
#   mountPath: /etc/example
#   readOnly: true